### ISSUE TITLE
Add name feature

### ISSUE THREAD

**Issue by cryolune** [The-Virtual-Dancers/Virtual_Dancers_Messenger#2]
Name field is really important.
Being a VD member no one will be able to recognize who added that message as everyone knows everything.

**Comment by isNan909** [comment]
I will work on this @theakhiljha Just to verify my understanding, I will add a name field along with the message.

**Comment by rahulchauhan049** [comment]
Either it'll randomly assign a name if no name is existing in the user's local storage, or ask for a nickname for the first time.
