### ISSUE TITLE
fix delete button

### ISSUE THREAD

**Issue by cryolune** [The-Virtual-Dancers/Virtual_Dancers_Messenger#3]
Fix the delete button so that no one will be able to delete messages shared by other members.

**Comment by PhilippeBarre** [comment]
Hello, please what is a shared message ? I don't see "share button" or something like this on your site https://todo-app-d0a0d.web.app/

**Comment by cryolune** [comment]
hey @PhilippeBarre by shared i meant that if User 1 is sending some messages using our web app then User 2 shouldn't have access to delete or modify the message from user 1.

**Comment by richardjob** [comment]
I'm working on this.

**Comment by cryolune** [comment]
cool @richardjob should i assign this to you?

**Comment by richardjob** [comment]
Yehh. do it
